name: openFDA
url: https://open.fda.gov

markdown: kramdown
kramdown:
  use_coderay: true
  coderay_line_numbers: nil
  parse_block_html: true

highlighter: pygments
permalink: /update/:title/
baseurl: ""

port: 80
host: 192.168.9.76
